name: my-first-flow
on:
  push:
    branches: [main]
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"
      - run: ls .*
      - uses: actions/checkout@v4
      - run: ls .*
